CREATE TABLE INGREDIENTS (
    INGREDIENT_CODE BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE MENU_ITEMS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    PRICE DOUBLE
);

CREATE TABLE MENU_ITEM_INGREDIENTS (
    menu_item_id BIGINT NOT NULL,
    ingredient_code BIGINT NOT NULL,
    quantity DOUBLE NOT NULL,
    unit VARCHAR(255) NOT NULL,
    PRIMARY KEY (menu_item_id, ingredient_code),
    FOREIGN KEY (menu_item_id) REFERENCES MENU_ITEMS(ID) ON DELETE CASCADE,
    FOREIGN KEY (ingredient_code) REFERENCES INGREDIENTS(INGREDIENT_CODE) ON DELETE CASCADE
);

CREATE TABLE PRODUCTS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    QUANTITY INT,
    PRICE DOUBLE,
    EXPIRY_DATE DATE,
    INGREDIENT_CODE BIGINT NOT NULL,
    FOREIGN KEY (INGREDIENT_CODE) REFERENCES INGREDIENTS(INGREDIENT_CODE) ON DELETE CASCADE
);

CREATE TABLE SUPPLIERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    CONTACT_INFO VARCHAR(500),
    MINIMUM_ORDER INT,
    DELIVERY_TIME INT,
    DESCRIPTION VARCHAR(500)
);

CREATE TABLE SUPPLIERS_INGREDIENTS (
    SUPPLIER_ID BIGINT NOT NULL,
    INGREDIENT_CODE BIGINT NOT NULL,
    PRIMARY KEY (SUPPLIER_ID, INGREDIENT_CODE),
    FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (INGREDIENT_CODE) REFERENCES INGREDIENTS(INGREDIENT_CODE) ON DELETE CASCADE
);

CREATE TABLE SUPPLIER_ORDER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    SUPPLIER_ID BIGINT NOT NULL,
    FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(ID) ON DELETE CASCADE,
    PRODUCT_ID BIGINT NOT NULL,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID) ON DELETE CASCADE,
    QUANTITY INT NOT NULL,
    STATUS VARCHAR(255),
    DATE_PLACED DATE,
    DATE_DELIVERED DATE
);

CREATE TABLE CUSTOMER_ORDER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    MENU_ITEM_ID BIGINT NOT NULL,
    DATE DATE NOT NULL,
    QUANTITY INT NOT NULL,
    FOREIGN KEY (MENU_ITEM_ID) REFERENCES MENU_ITEMS(ID) ON DELETE CASCADE
);
