CREATE TABLE INGREDIENTS (
    INGREDIENT_CODE VARCHAR(255) PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE MENU_ITEMS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    PRICE DOUBLE
);

CREATE TABLE MENU_ITEM_INGREDIENTS (
    menu_item_id BIGINT NOT NULL,
    ingredient_code VARCHAR(255) NOT NULL,
    quantity DOUBLE NOT NULL,
    unit VARCHAR(255) NOT NULL,
    PRIMARY KEY (menu_item_id, ingredient_code),
    FOREIGN KEY (menu_item_id) REFERENCES MENU_ITEMS(id) ON DELETE CASCADE,
    FOREIGN KEY (ingredient_code) REFERENCES INGREDIENTS(ingredient_code) ON DELETE CASCADE
);

CREATE TABLE PRODUCTS (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  QUANTITY INT,
  PRICE DOUBLE,
  EXPIRY_DATE DATE
);

CREATE TABLE SUPPLIERS (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  CONTACT_INFO VARCHAR(500),
  MINIMUM_ORDER INT,
  DELIVERY_TIME INT,
  DESCRIPTION VARCHAR(500)
);

CREATE TABLE SUPPLIERS_PRODUCTS (
  SUPPLIER_ID BIGINT NOT NULL,
  PRODUCT_ID BIGINT NOT NULL,
  PRIMARY KEY (SUPPLIER_ID, PRODUCT_ID),
  FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(ID),
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID)
);

CREATE TABLE SUPPLIER_ORDER (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  SUPPLIER_ID BIGINT NOT NULL,
  FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(ID),
  PRODUCT_ID BIGINT NOT NULL,
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID),
  QUANTITY INT NOT NULL,
  STATUS VARCHAR(255),
  DATE_PLACED DATE,
  DATE_DELIVERED DATE
);

